name: 通用表单
title: "NetFox.Wiki: {name}"
description: 通用提交单
labels: [ "netfox_wiki" ]
body:
  - type: input
    id: name
    attributes:
      label: 名称
      description: 名称
    validations:
      required: true